// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.GestionPagos.Infraestructura.Persistencia;

#nullable disable

namespace SB.GestionPagos.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(GestionPagosDbContext))]
    [Migration("20260830214945_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SB.GestionPagos.Dominio.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoEmpleado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ApellidoPaterno")
                        .HasDatabaseName("IX_Empleados_ApellidoPaterno");

                    b.HasIndex("Departamento")
                        .HasDatabaseName("IX_Empleados_Departamento");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Empleados_Estado");

                    b.HasIndex("NumeroSeguroSocial")
                        .IsUnique()
                        .HasDatabaseName("IX_Empleados_NumeroSeguroSocial");

                    b.ToTable("Empleados", (string)null);

                    b.HasDiscriminator<string>("TipoEmpleado").HasValue("Empleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SB.GestionPagos.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_NombreUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HashContrasena = "$2a$12$iA7cg2RZfZbgY6/shX4Py.bPfze.s9Pv.YDJ7sJHKa9ds/MBsXHVa",
                            NombreUsuario = "admin",
                            Rol = 1
                        },
                        new
                        {
                            Id = 2,
                            HashContrasena = "$2a$12$RM7LaYWnevG9wPyWUyxQSe4C/3G3F0Ek7i.50I0zSurYpSIPlnWRa",
                            NombreUsuario = "usuario",
                            Rol = 2
                        });
                });

            modelBuilder.Entity("SB.GestionPagos.Dominio.Entidades.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("SB.GestionPagos.Dominio.Entidades.Empleado");

                    b.Property<decimal>("SalarioSemanal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Asalariado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoPaterno = "Reyes",
                            Departamento = "Tecnología",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000001-1",
                            PrimerNombre = "Ana",
                            SalarioSemanal = 32500.00m
                        },
                        new
                        {
                            Id = 2,
                            ApellidoPaterno = "Mejía",
                            Departamento = "Finanzas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000002-2",
                            PrimerNombre = "Carlos",
                            SalarioSemanal = 28000.00m
                        },
                        new
                        {
                            Id = 3,
                            ApellidoPaterno = "Fernández",
                            Departamento = "Recursos Humanos",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000003-3",
                            PrimerNombre = "Lucía",
                            SalarioSemanal = 24500.00m
                        },
                        new
                        {
                            Id = 4,
                            ApellidoPaterno = "Guzmán",
                            Departamento = "Operaciones",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000004-4",
                            PrimerNombre = "Pedro",
                            SalarioSemanal = 21000.00m
                        });
                });

            modelBuilder.Entity("SB.GestionPagos.Dominio.Entidades.EmpleadoAsalariadoPorComision", b =>
                {
                    b.HasBaseType("SB.GestionPagos.Dominio.Entidades.Empleado");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaComision")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("TarifaComision");

                    b.Property<decimal>("VentasBrutas")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VentasBrutas");

                    b.HasDiscriminator().HasValue("AsalariadoPorComision");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            ApellidoPaterno = "Rosario",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000013-3",
                            PrimerNombre = "Patricia",
                            SalarioBase = 18000.00m,
                            TarifaComision = 0.0500m,
                            VentasBrutas = 210000.00m
                        },
                        new
                        {
                            Id = 14,
                            ApellidoPaterno = "Almonte",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000014-4",
                            PrimerNombre = "Luis",
                            SalarioBase = 20000.00m,
                            TarifaComision = 0.0450m,
                            VentasBrutas = 156300.00m
                        },
                        new
                        {
                            Id = 15,
                            ApellidoPaterno = "Batista",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000015-5",
                            PrimerNombre = "Sofía",
                            SalarioBase = 16500.00m,
                            TarifaComision = 0.0625m,
                            VentasBrutas = 87400.25m
                        },
                        new
                        {
                            Id = 16,
                            ApellidoPaterno = "Encarnación",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000016-6",
                            PrimerNombre = "Ramón",
                            SalarioBase = 25000.00m,
                            TarifaComision = 0.0350m,
                            VentasBrutas = 305000.00m
                        });
                });

            modelBuilder.Entity("SB.GestionPagos.Dominio.Entidades.EmpleadoPorComision", b =>
                {
                    b.HasBaseType("SB.GestionPagos.Dominio.Entidades.Empleado");

                    b.Property<decimal>("TarifaComision")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("TarifaComision");

                    b.Property<decimal>("VentasBrutas")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VentasBrutas");

                    b.HasDiscriminator().HasValue("PorComision");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            ApellidoPaterno = "Vargas",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000009-9",
                            PrimerNombre = "Elena",
                            TarifaComision = 0.0800m,
                            VentasBrutas = 185000.00m
                        },
                        new
                        {
                            Id = 10,
                            ApellidoPaterno = "Núñez",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000010-0",
                            PrimerNombre = "Rafael",
                            TarifaComision = 0.0650m,
                            VentasBrutas = 240500.00m
                        },
                        new
                        {
                            Id = 11,
                            ApellidoPaterno = "Ortiz",
                            Departamento = "Ventas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000011-1",
                            PrimerNombre = "Carmen",
                            TarifaComision = 0.1000m,
                            VentasBrutas = 98750.50m
                        },
                        new
                        {
                            Id = 12,
                            ApellidoPaterno = "Polanco",
                            Departamento = "Ventas",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000012-2",
                            PrimerNombre = "Andrés",
                            TarifaComision = 0.0750m,
                            VentasBrutas = 132000.00m
                        });
                });

            modelBuilder.Entity("SB.GestionPagos.Dominio.Entidades.EmpleadoPorHoras", b =>
                {
                    b.HasBaseType("SB.GestionPagos.Dominio.Entidades.Empleado");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("SueldoPorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PorHoras");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            ApellidoPaterno = "Santos",
                            Departamento = "Operaciones",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000005-5",
                            PrimerNombre = "María",
                            HorasTrabajadas = 40.00m,
                            SueldoPorHora = 350.00m
                        },
                        new
                        {
                            Id = 6,
                            ApellidoPaterno = "Peña",
                            Departamento = "Operaciones",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000006-6",
                            PrimerNombre = "José",
                            HorasTrabajadas = 46.50m,
                            SueldoPorHora = 420.00m
                        },
                        new
                        {
                            Id = 7,
                            ApellidoPaterno = "Jiménez",
                            Departamento = "Tecnología",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000007-7",
                            PrimerNombre = "Rosa",
                            HorasTrabajadas = 38.00m,
                            SueldoPorHora = 550.00m
                        },
                        new
                        {
                            Id = 8,
                            ApellidoPaterno = "Castillo",
                            Departamento = "Operaciones",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroSeguroSocial = "001-0000008-8",
                            PrimerNombre = "Miguel",
                            HorasTrabajadas = 40.00m,
                            SueldoPorHora = 310.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
