<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SB.GestionPagos.Dominio\SB.GestionPagos.Dominio.csproj" />
    <ProjectReference Include="..\SB.GestionPagos.Aplicacion\SB.GestionPagos.Aplicacion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.*" />
  </ItemGroup>

</Project>
